AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - 'ember-frontend/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'app/api/**/*'

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Exclude:
    - 'lib/**/*'
